feat: реализация ТЗ14
brnvrn/java-shareit pull request #1
Opened 2024-08-04 16:28 UTC by brnvrn

2024-08-06 11:18 UTC, db-exp requested changes

2024-08-06 11:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotBlank
+ Size

2024-08-06 11:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    @NotBlank
+ Size

2024-08-06 11:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    @NotBlank(message = "Описание не должно быть пустым")
Size

2024-08-06 11:18 UTC, db-exp commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +    @NotBlank(message = "Описание не должно быть пустым")
Size

2024-08-07 09:28 UTC, brnvrn commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +public class ItemServiceImpl implements ItemService {
еще пока не изучали

2024-08-08 10:50 UTC, db-exp approved these changes

2024-08-09 15:24 UTC, merged